### ISSUE TITLE
本地无法运行

### ISSUE THREAD

**Issue by MEclipse1** [yeshuang2/student-attendance-management#1]
缺少表数据 本地无法运行。
不知能否将表结构也上传上来。

**Comment by yeshuang2** [comment]
付费 需要联系主页


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeshuang2/student-attendance-management"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月11日(星期一) 晚上6:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yeshuang2/student-attendance-management] 本地无法运行 (Issue #1)





 
缺少表数据 本地无法运行。
 不知能否将表结构也上传上来。
